DATABASE_URL = "postgresql://postgres.avzcqgwerokdyzdpflnz:Just72506537%40@aws-1-eu-west-1.pooler.supabase.com:6543/postgres"
# Email Alert Configuration
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 465 #the blocked port 587
SENDER_EMAIL = "wirkudivine@gmail.com"
SENDER_PASSWORD = "pzygynylgskbusnt"

# List of Maintenance Leads (Comma-separated)
#MAINTENANCE_LEADS = "justice.wiruu.ext@holcim.com, maintenance.head@holcim.com"
MAINTENANCE_LEADS = "justice.wiruu.ext@holcim.com"